'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DetalleEmpresa
    
    '''<summary>
    '''lblTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitulo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtEditarEmpresa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditarEmpresa As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNombre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNombre As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtRFC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRFC As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cbxRegimenFiscal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxRegimenFiscal As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''txtCURP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCURP As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnTriggerUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTriggerUpdate As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''txtCalle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCalle As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNumExt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumExt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNumInt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumInt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCalles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCalles As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtColonia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtColonia As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCP As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cbxPais control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxPais As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''cbxEstado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxEstado As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''txtMunicipio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMunicipio As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCalleEmision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCalleEmision As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNumExtEmision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumExtEmision As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNumIntEmision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumIntEmision As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCallesEmision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCallesEmision As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtColoniaEmision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtColoniaEmision As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCPEmision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCPEmision As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cbxPaisEmision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxPaisEmision As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''cbxEstadoEmision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxEstadoEmision As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''txtMunicipioEmision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMunicipioEmision As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNombreComercial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNombreComercial As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLogo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLogo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''binaryLogo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents binaryLogo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''fuLogo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuLogo As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''output control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents output As Global.System.Web.UI.HtmlControls.HtmlImage
    
    '''<summary>
    '''txtMensaje control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMensaje As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTelefonos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTelefonos As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCorreo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCorreo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTitulo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtContenido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContenido As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtClavePrivada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClavePrivada As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''binaryKey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents binaryKey As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''fuClavePrivada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuClavePrivada As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''txtPassClavePrivada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPassClavePrivada As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSelloDigital control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSelloDigital As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''binaryCert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents binaryCert As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''fuSelloDigital control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuSelloDigital As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''repContactos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents repContactos As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''txtNombreContacto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNombreContacto As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cbxTipoContacto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxTipoContacto As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''txtTelefonoFijo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTelefonoFijo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtMovil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMovil As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCorreoContacto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCorreoContacto As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPuesto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPuesto As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnAgregarContacto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAgregarContacto As Global.System.Web.UI.WebControls.Button
End Class
